name: Deploy AWS Lambda

on:
  push:
    branches:
      - main
    paths:
      - "lambda/**"
  workflow_dispatch:

jobs:
  deploy-lambda:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v2
        with:
          python-version: '3.12'
      - run: |
          python -m pip install --upgrade pip
          pip install -r lambda/requirements.txt -t lambda/
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2
      - run: |
          cd lambda
          zip -r lambda.zip .
          aws lambda update-function-code \
            --function-name test-cicd-lambda \
            --zip-file fileb://lambda.zip \
            --region eu-west-2
