---
name: Deploy AWS Lambda # test

on:
  push:
    branches:
      - main
    # Only trigger if files in the "lambda/" folder change.
    # Remove or comment out the lines below if you want to deploy on every push to main.
    paths:
      - "lambda/**"
  # Allows you to manually trigger the workflow from the "Actions" tab
  workflow_dispatch:

jobs:
  deploy-lambda:
    runs-on: ubuntu-latest
    steps:
      # 1. Check out your code from GitHub
      - name: Check out repository
        uses: actions/checkout@v3

      # 2. Set up Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      # 3. Install dependencies into lambda/ folder
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r lambda/requirements.txt -t lambda/

      # 4. Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2

      # 5. Zip & Update Lambda code
      - name: Deploy to AWS Lambda
        run: |
          cd lambda
          zip -r lambda.zip .
          aws lambda update-function-code \
            --function-name test-cicd-lambda \
            --zip-file fileb://lambda.zip \
            --region eu-west-2
